site_name: "x64dbg Automate"
nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Quickstart": quickstart.md
  - "Api Reference":
    - "Session Control": api/session-control.md
    - "Debug Control": api/debug-control.md
    - "Memory Control": api/memory-control.md
    - "Breakpoints": api/breakpoints.md
    - "Registers and Expressions": api/registers-expressions.md
    - "Assembling and Disassembling": api/assembler-disassembler.md
    - "Commands and Extensibility": api/commands.md
    - "Labels, Comments, Bookmarks": api/annotations.md
plugins:
  - search
  - mkdocstrings
  - autorefs