site_name: "x64dbg Automate"
nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Quickstart": quickstart.md
  - "Api Reference":
    - "Session Control": sessions.md
plugins:
  - search
  - mkdocstrings
  - autorefs