site_name: "x64dbg Automate"
nav:
  - "Home": index.md
  - "Installation": installation.md
  - "Quickstart": quickstart.md
  - "Api Reference":
    - "Session Control": api/sessions.md
    - "Debug Control": api/debug-control.md
    - "Registers and Memory": api/reg-and-mem.md
plugins:
  - search
  - mkdocstrings
  - autorefs